name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm i
    - name: Build scripts
      run: npm run build
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        port: 22
        key: ${{ secrets.DEPLOY_SSHKEY }}
        source: "css/,img/,index.html,js/,node_modules/,package-lock.json,package.json,php/"
        target: ${{ secrets.DEPLOY_TARGET }}
